### ISSUE TITLE
[BUG] [ERROR] Key for part NaN download error/[ERROR] Track not selected 

### ISSUE THREAD

**Issue by Ryahn** [anidl/funimation-downloader-nx#19] opened 2020-07-16 01:00 UTC
** Main info: **

Script version: 4.6.0
Show ID: 36842
Episode ID: 1

** Additional Info: **
```
[ERROR] Key for part NaN download error:
        Cannot read property 'p' of undefined
[ERROR] Key for part NaN download error:
        Cannot read property 'p' of undefined
[ERROR] 2 parts not downloaded
[ERROR] DL Stats: {"first":0,"total":180,"completed":10}
```

Using `node funi.js -s 36842 -e 1 -q 0 --mks`

I also get `[ERROR] Track not selected` when using on another anime `node funi.js -s 1108396 -e 2`

**Comment by magicsokka** [comment] 2020-07-16 13:55
I have the same issue...

**Comment by Depressee-Chan** [comment] 2020-07-22 02:42
COMMAND: 
	node funi -s 54210 -e 1-11

OUTPUT:
	[ERROR] Key for part NaN download error:
        	Cannot read property 'p' of undefined
	[ERROR] Key for part NaN download error:
        	Cannot read property 'p' of undefined
	[ERROR] 2 parts not downloaded
	[ERROR] DL Stats: {"first":0,"total":170,"completed":10}

I get the same error too with the command and output above.

**Comment by Student2503** [comment] 2020-07-24 12:17
same

**Comment by XxUnkn0wnxX** [comment] 2020-07-26 18:50
same issue here @anidl 

```
[ERROR] Key for part NaN download error:
	Cannot read property 'p' of undefined
[ERROR] Key for part NaN download error:
	Cannot read property 'p' of undefined
[ERROR] 2 parts not downloaded
[ERROR] DL Stats: {"first":0,"total":172,"completed":10}
```

it seems it cannot continue, it downloads the 1st 10 parts then fails, then if you retry it resumes and DL's the next 10 parts then fails..

**Comment by XxUnkn0wnxX** [comment] 2020-08-04 08:19
ok it seems the issue is with the server it selects `funiprod.akamaized.net` but doing EG `node funi -s 825013 -e 35 -x 2` (Fruits Basket S2E10 Dub) no issues
`-x` is the server selection
![Screen Shot 2020-08-04 at 6 18 32 pm](https://user-images.githubusercontent.com/2242880/89270642-fa319c00-d67e-11ea-83c4-3741e6890614.jpg)
just do `-x 2` or `-x 3`
while by default it does `-x 1` which is the `funiprod.akamaized.net` server.

**Comment by shinji257** [comment] 2020-08-25 18:43
One way to handle this (if it is possible) is have it retry using the next server on the list rather than hard aborting and moving to the next episode (if any).

**Comment by nijave** [comment] 2020-09-09 19:53
Opened https://github.com/seiya-npm/hls-download/issues/9 since it looks like there's a problem with that module's ability to find the next batch of parts to download

**Closed** 2020-10-04 09:07 UTC
Labels: bug
